name: Scrape latest exchange rate data

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '4 0 * * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - name: Check out this repo
      uses: actions/checkout@v2
    - name: Fetch latest currency rates
      env:
        APP_ID: ${{ secrets.APP_ID}}
      run: |-
        CSV_MONTHLY="rates/$(date +'%Y%m').csv"
        curl -s "https://openexchangerates.org/api/latest.json?app_id=$APP_ID" | jq -r '. as $R | $R.timestamp | strftime("%Y-%m-%d") as $ts | ($R.rates | to_entries[] | [$ts, .key, .value]) | @csv' >> $CSV_MONTHLY
        cat $CSV_MONTHLY | awk -F, '!a[$1$2]++' | tee $CSV_MONTHLY
    - name: Fetch currency code
      run: |-
        curl -s "https://openexchangerates.org/api/currencies.json" | jq -r '. | to_entries[] | ["Code", "Fullname"], [.key, .value] | @csv' > currencies.csv
    - name: Commit and push if it changed
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "Latest data: ${timestamp}" || exit 0
        git push
